### ISSUE TITLE
docs/api

### ISSUE THREAD

**Issue by vladthecodeimpaler** [WaveEngine/Feedback#1]
Love the new v3

The project couldnt build so I had to manually add the env MSBuildSDKsPath and install the .net dev kit

Most importantly the docs are down so I cant browse the api and for some reason it is not included with the installer
http://doc.waveengine.net/

Keep up the good work!

**Comment by jcant0n** [comment]
Thank for your feedback, We will try to fix it as soon as possible this week.

**Comment by danielcaceresm** [comment]
Thanks for your interest @vladthecodeimpaler. The documentation site is up again, and we have added the API documentation for the version 3.0 preview. We will start to update the recipes and samples when the stable release goes public.
