### ISSUE TITLE
Extraño comportamiento al seleccionar los ejes

### ISSUE THREAD

**Issue by gabrielgt** [WaveEngine/Feedback#10]
Hola,

Al intentar seleccionar alguno de los ejes de una entidad, por ejemplo para moverla o para escalarla, la posición del cursor del ratón que hace que se resalte el eje es errática. En esta imagen el eje azul está seleccionado, y sin embargo el ratón (aunque no se ve) está en la cuadrícula debajo del eje rojo.

![image](https://user-images.githubusercontent.com/3408827/76646499-5d4d5580-655b-11ea-934b-f8e41cf88872.png)

¡Saludos!

**Comment by danielcaceresm** [comment]
Hola @gabrielgt,

Efectivamente la preview 3 tiene un problema en monitores con escala distinta de 100%. En la siguiente actualización estará arreglado. De momento, la única solución es usar escala 100%.
Te informo por aquí cuando publiquemos la versión que lo soluciona.

Un saludo.

**Comment by danielcaceresm** [comment]
Hola @gabrielgt,

Acabamos de publicar una actualización de la preview 3, la versión 3.0.0.4636-preview3, que soluciona este bug.
Cierro la issue, no dudes en volver a abrirla si el bug sigue.

Muchas gracias.

**Comment by gabrielgt** [comment]
Comprobado. Ya funciona perfectamente.

¡Gracias!
