### ISSUE TITLE
Chinese Letters In TextComponent

### ISSUE THREAD

**Issue by aspernol** [WaveEngine/Feedback#11]
Hi,
I'm using WaveEngine v2.4.1.
I tried to display some chinese letters but all I get are '*' characters instead. I used the Wave Visual Editor, imported two fronts (one of them: Arial), created a 3DText and just pasted the chinese characters into the text field in the properties of the TextComponent. The result was '***' instead of the three characters. The property grid displays the characters correctly.

How can I display the chinese characters?
Best regards,
Andreas.

**Comment by minolo** [comment]
Hi there!

If you are sure that the font supports chinese characters, it might be that the TextComponent does not :(

You can try using Noesis to create a panel that shows that text. We wrote two articles to get you started using Noesis in Wave Engine 2.4

[Getting started with NoesisGUI](https://geeks.ms/waveengineteam/2017/08/22/getting-started-with-noesisgui-in-waveengine-2-4-0/)
[Setting up a Blend project](https://geeks.ms/waveengineteam/2017/09/21/setting-up-a-blend-project-to-design-your-own-gui-with-noesisgui-in-waveengine/)

Once that is set up, you can just add a TextBlock to your XAML, with the text you want to show.

I hope this can be helpful to you. Best regards.
