### ISSUE TITLE
SharpDXException when creating or opening a project in WaveEngine 3 Editor

### ISSUE THREAD

**Issue by joseluisc** [WaveEngine/Feedback#17]
Hi,

I'm experiencing a blocking problem when starting WaveEngine 3 editor, version 3.0.0.4932.
A SharpDx exception appears at log and "Assets Hierarchy" and "Assets Details" panels stay unresponsive.
I have attached the exception log and my computer's DxDiag output.

Thank you and best regards.

Jose Luis

**Unhandled Exception: SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.**
 at SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:line 195
at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels) in C:\projects\sharpdx\Source\SharpDX.Direct3D11\Device.cs:line 669
at WaveEngine.DirectX11.DX11GraphicsContext.CreateDeviceInternal() in C:\MyAgent\_work\3\s\src\Engine\Rendering\WaveEngine.DirectX11\DX11GraphicsContext.cs:line 200
at WaveEngine.Runner.Game.Run(CancellationToken cancellationToken) in C:\MyAgent\_work\3\s\src\Tools\Editor\WaveEngine.Runner\Game.cs:line 109
 at WaveEngine.Runner.Game.Run(CancellationToken cancellationToken) in C:\MyAgent\_work\3\s\src\Tools\Editor\WaveEngine.Runner\Game.cs:line 109
  at WaveEngine.Runner.Program.Main(String[] args) in C:\MyAgent\_work\3\s\src\Tools\Editor\WaveEngine.Runner\Program.cs:line 0
The project has some errors that prevents it to be executed, check the log and reload the project when they are fixed.

**---------------------------------------------------------------------------------------------------------**

**"DxDiag" output is:**

------------------
System Information
------------------
      Time of this report: 5/9/2020, 11:50:29
             Machine name: WESL190200092
               Machine Id: {6D01571E-6837-4714-8698-CC51142F612E}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
                 Language: English (Regional Setting: English)
      System Manufacturer: HP
             System Model: HP ZBook 17 G3
                     BIOS: N81 Ver. 01.38 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 CPUs), ~2.7GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32648MB RAM
                Page File: 10597MB used, 26914MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
           DxDiag Version: 10.00.17763.0001 64bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
      Display Tab 2: No problems found.
      Display Tab 3: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
        Sound Tab 3: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
           Card name: NVIDIA Quadro M3000M
        Manufacturer: NVIDIA
           Chip type: Quadro M3000M
            DAC type: Integrated RAMDAC
         Device Type: Full Device
          Device Key: Enum\PCI\VEN_10DE&DEV_13FA&SUBSYS_80D6103C&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 20377 MB
    Dedicated Memory: 4053 MB
       Shared Memory: 16323 MB
        Current Mode: 1920 x 1080 (32 bit) (60Hz)
         HDR Support: Not Supported
    Display Topology: Extend
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.651367,0.337891), Green(0.318359,0.612305), Blue(0.151367,0.065430), White Point(0.313477,0.329102)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: Generic PnP Monitor
       Monitor Model: HP Z23n G2
          Monitor Id: HPN347A
         Native Mode: 1920 x 1080(p) (60.000Hz)
         Output Type: Displayport External
Monitor Capabilities: HDR Not Supported
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: Not Supported
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll
 Driver File Version: 24.21.0014.1163 (English)
      Driver Version: 24.21.14.1163
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.4
 Graphics Preemption: DMA
  Compute Preemption: DMA
            Miracast: Not Supported by Graphics driver
 Hybrid Graphics GPU: Discrete
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:False Declarative:False 
   Driver Attributes: Final Retail
    Driver Date/Size: 9/18/2018 2:00:00 AM, 952824 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: {D7B71E3E-50BA-11CF-0777-D8A01BC2D535}
           Vendor ID: 0x10DE
           Device ID: 0x13FA
           SubSys ID: 0x80D6103C
         Revision ID: 0x00A1
  Driver Strong Name: oem109.inf:0f066de3717875ab:Section078:24.21.14.1163:pci\ven_10de&dev_13fa&subsys_80d6103c
      Rank Of Driver: 00D10001
         Video Accel: 
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeVC1_D2010  DXVA2_ModeVC1_VLD  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeMPEG4pt2_VLD_Simple  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  
   Deinterlace Caps: [*Skipped*]
        D3D9 Overlay: Supported
             DXVA-HD: Supported
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 1
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

           Card name: NVIDIA Quadro M3000M
        Manufacturer: NVIDIA
           Chip type: Quadro M3000M
            DAC type: Integrated RAMDAC
         Device Type: Full Device
          Device Key: Enum\PCI\VEN_10DE&DEV_13FA&SUBSYS_80D6103C&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 20377 MB
    Dedicated Memory: 4053 MB
       Shared Memory: 16323 MB
        Current Mode: 1920 x 1080 (32 bit) (60Hz)
         HDR Support: Not Supported
    Display Topology: Extend
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.651367,0.337891), Green(0.318359,0.612305), Blue(0.151367,0.065430), White Point(0.313477,0.329102)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: Generic PnP Monitor
       Monitor Model: HP Z23n G2
          Monitor Id: HPN347A
         Native Mode: 1920 x 1080(p) (60.000Hz)
         Output Type: Displayport External
Monitor Capabilities: HDR Not Supported
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: Not Supported
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvblwi.inf_amd64_af748320115c7cba\nvldumdx.dll
 Driver File Version: 24.21.0014.1163 (English)
      Driver Version: 24.21.14.1163
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.4
 Graphics Preemption: DMA
  Compute Preemption: DMA
            Miracast: Not Supported by Graphics driver
 Hybrid Graphics GPU: Discrete
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:False Declarative:False 
   Driver Attributes: Final Retail
    Driver Date/Size: 9/18/2018 2:00:00 AM, 952824 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: {D7B71E3E-50BA-11CF-0777-D8A01BC2D535}
           Vendor ID: 0x10DE
           Device ID: 0x13FA
           SubSys ID: 0x80D6103C
         Revision ID: 0x00A1
  Driver Strong Name: oem109.inf:0f066de3717875ab:Section078:24.21.14.1163:pci\ven_10de&dev_13fa&subsys_80d6103c
      Rank Of Driver: 00D10001
         Video Accel: 
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeVC1_D2010  DXVA2_ModeVC1_VLD  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeMPEG4pt2_VLD_Simple  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  
   Deinterlace Caps: [*Skipped*]
        D3D9 Overlay: Supported
             DXVA-HD: Supported
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 1
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

           Card name: Intel(R) HD Graphics 530
        Manufacturer: Intel Corporation
           Chip type: Intel(R) HD Graphics Family
            DAC type: Internal
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_8086&DEV_191B&SUBSYS_80D6103C&REV_06
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 16451 MB
    Dedicated Memory: 128 MB
       Shared Memory: 16323 MB
        Current Mode: Unknown
         HDR Support: Unknown
    Display Topology: Unknown
 Display Color Space: Unknown
     Color Primaries: Unknown
   Display Luminance: Unknown
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64_skl_kit127358.inf_amd64_2b94ab23909d4e28\igdumdim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64_skl_kit127358.inf_amd64_2b94ab23909d4e28\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64_skl_kit127358.inf_amd64_2b94ab23909d4e28\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64_skl_kit127358.inf_amd64_2b94ab23909d4e28\igd12umd64.dll
 Driver File Version: 23.20.0016.5018 (English)
      Driver Version: 23.20.16.5018
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.1
 Graphics Preemption: Triangle
  Compute Preemption: Thread
            Miracast: Supported
 Hybrid Graphics GPU: Integrated
      Power P-states: Not Supported
      Virtualization: Not Supported
          Block List: No Blocks
  Catalog Attributes: Universal:N/A Declarative:N/A 
   Driver Attributes: Final Retail
    Driver Date/Size: 3/27/2018 2:00:00 AM, 1976656 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: Unknown
           Vendor ID: 0x8086
           Device ID: 0x191B
           SubSys ID: 0x80D6103C
         Revision ID: 0x0006
  Driver Strong Name: oem80.inf:5f63e5340a14bf6c:iSKLD_w10_DS:23.20.16.5018:pci\ven_8086&dev_191b&subsys_80d6103c
      Rank Of Driver: 00D10001
         Video Accel: Unknown
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeMPEG2_IDCT  DXVA2_ModeVC1_D2010  DXVA2_ModeWMV9_IDCT  DXVA2_ModeVC1_IDCT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeH264_VLD_Multiview_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeHEVC_VLD_Main10  
      Deinterlace Caps: n/a
        D3D9 Overlay: Unknown
             DXVA-HD: Unknown
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 0
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

**Comment by drigon01** [comment]
Hi @joseluisc I've just hit this issue too.
A bit of searching on the sharpdx repo's issue tracker led me to this:
https://docs.microsoft.com/hu-hu/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features?redirectedfrom=MSDN

In my case this was resolved by adding the graphic tools optional feature on my win10
![image](https://user-images.githubusercontent.com/3844085/81761658-7f4e5000-9498-11ea-82cc-696a9c90a649.png)

**Comment by joseluisc** [comment]
Hi @drigon01 ,

I knew about that fix and I tried before. 
But, after selecting the feature to install, Windows looks like installing for a while and then nothing happens.

![image](https://user-images.githubusercontent.com/16689761/82118822-e9594480-9779-11ea-99fc-a934b9ac316f.png)

It's not my personal computer but my company's. I'm thinking this could be an admin policy from my computer but I had no problems with any other engine installed before.

Best regards

JL

**Comment by jcant0n** [comment]
Hi @joseluisc 

Graphics Tools is now a prerequisite of WaveEngine 3.0 to be able to debug DX11 code and you need an admin account to install it.

Maybe using other APIs like OpenGL this isn't necessary
