### ISSUE TITLE
Wave Project not running in Wave Home Page

### ISSUE THREAD

**Issue by acnagrellos** [WaveEngine/Feedback#21]
When I running WaveEngine, click on Open a project and try to open it I get this error message

The project <projectname> can not be opened.

The editor process 'C:\Users\<waveroute>\WaveEngine.Editor.WPF.exe' can not be started.

![image](https://user-images.githubusercontent.com/6035030/82563497-7be15580-9b77-11ea-8769-ebfcb890074d.png)

If I open the project in file explorer, the project run correctly and WaveEngine is open.

**Comment by acnagrellos** [comment]
My WaveEngine version is 3.0.0.4932

**Comment by danielcaceresm** [comment]
Hi @acnagrellos, I apologize for the delay in the response. You are still getting this error? From you created this issue we had updated the Editor Launcher application, and we had addressed some related bugs.

**Comment by danielcaceresm** [comment]
I will close the issue due to inactivity.
