### ISSUE TITLE
Where is UI in waveengine 3?

### ISSUE THREAD

**Issue by Thaina** [WaveEngine/Feedback#22]
Is it not released yet or we have new UI system?

**Comment by minolo** [comment]
Hi there @Thaina!

The way of doing UI in WaveEngine 3 is through the use of NoesisGUI. The engine provides some components to aid in the development of 2D UIs, which can then be used even in a 3D scene as planar interfaces.

We made a couple of tutorials for WaveEngine 2.4 regarding the creation of interfaces using NoesisGUI. They are a bit outdated but most parts still apply. There are some changes like the name of the components being changed.

[Getting started with NoesisGUI](https://geeks.ms/waveengineteam/2017/08/22/getting-started-with-noesisgui-in-waveengine-2-4-0/)
[Setting up a Blend project](https://geeks.ms/waveengineteam/2017/09/21/setting-up-a-blend-project-to-design-your-own-gui-with-noesisgui-in-waveengine/)

We are also working on a toolkit to make 3D UIs in AR/VR, which you can find here: [MixedRealityToolkit-WaveEngine](https://github.com/WaveEngine/MixedRealityToolkit-WaveEngine)

I hope this is helpful to you!
