### ISSUE TITLE
it just Crash's on start up 

### ISSUE THREAD

**Issue by MuktadaCreations** [WaveEngine/Feedback#3]
when u crate a project and dual click it to open the editor for it it juts said 

The selected project cant be opened  C:/***********
-the wave engine editor will be Closed.

any ideas for fixing it

**Comment by danielcaceresm** [comment]
Hi MuktadaCreations,

Thanks you for reporting the issue.
This is a known error when creating a project with spaces in the path. It will be solved in next releases.
To work around this issue you can create a project in a folder whose path does not contain any spaces, and also setting a name without spaces.

Sorry for the inconveniences.

**Comment by danielcaceresm** [comment]
We have released a new version of Wave Engine that fixes the problem with creating a project in a path with spaces and adds a validation in the project name (only letters, numbers and underscores are valid).
You must ensure you have the latest Wave Engine Launcher version installed (3.0.0.3717) by clicking in the gear icon of the Launcher. If you don't have the latest version, please restart the Launcher so it can auto-update.
After this, be sure to create projects using at least version 3.0.0.3718-preview2.

I am closing this one but feel free to respond back and I will be happy to assist you.
