### ISSUE TITLE
Texture2D in 3.1?

### ISSUE THREAD

**Issue by delinx32** [WaveEngine/Feedback#34]
Can't find an equivalent to the Texture2D class in 3.1.  Has it been changed to a new class name?

**Comment by vicfergar** [comment]
Hi @delinx32,

At Wave Engine 3.x all texture types has been unified in a single **Texture** class. You can find an example of a Texture2D [here](https://github.com/WaveEngine/LowLevelAPIDemo/blob/5194a7fef6f44a1210767f49ef2070c1f4e52a93/src/LowLevelAPI/RenderToTexture/RenderToTextureTest.cs#L143).

**Comment by vicfergar** [comment]
I will close the issue due to inactivity.
