### ISSUE TITLE
Expected to work on Linux?

### ISSUE THREAD

**Issue by ptupitsyn** [WaveEngine/Feedback#40]
Hi,

Looking at the diagram in the [blog post](https://geeks.ms/waveengineteam/2020/12/05/introducing-waveengine-3-1-based-on-net-5/), I expected the [samples](https://github.com/WaveEngine/Samples) to run on Linux:

![what we are building](https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2020/11/whatwearebuilding.png)

I have .NET 5 and SDL 2 installed, and I can build the source code, but it fails on startup:
```
/usr/share/dotnet/dotnet /home/pavel/w/tests/LowLevelAPIDemo/src/LowLevelAPI/DrawTriangle/bin/Debug/net5.0/DrawTriangle.dll
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'dxgi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdxgi.dll: cannot open shared object file: No such file or directory
   at SharpDX.DXGI.DXGI.CreateDXGIFactory2_(Int32 param0, Void* param1, Void* param2)
   at SharpDX.DXGI.DXGI.CreateDXGIFactory2(Int32 flags, Guid riid, IntPtr& factoryOut)
   at SharpDX.DXGI.Factory2..ctor(Boolean debug)
   at WaveEngine.DirectX11.DX11GraphicsContext.CreateDeviceInternal()
   at WaveEngine.Common.Graphics.GraphicsContext.CreateDevice(ValidationLayer validationLayer)
   at Common.VisualTestDefinition.CreateGraphicsContext(Nullable`1 swapChainDescriptor, Nullable`1 prefferedBackend) in /home/pavel/w/tests/LowLevelAPIDemo/src/LowLevelAPI/Common/VisualTestDefinition.cs:line 91
   at DrawTriangle.Program.Main() in /home/pavel/w/tests/LowLevelAPIDemo/src/LowLevelAPI/DrawTriangle/Program.cs:line 34

Process finished with exit code 134.
```

SharpDX is Windows-only, obviously - am I doing something wrong? Is Linux support coming later?

Thanks!

**Comment by jeangit** [comment]
SharpDX is a wrapper for directX, so obviously no linux here (http://sharpdx.org/). Moreover, it is deprecated. On the sharpdx website, they say  « NOTE: As of 29 Mar 2019, SharpDX is no longer being under development or maintenance ».

I was thinking maybe we could rebuild the samples for linux with the editor.
But the editor's installer is only available for windows and macos.

Nothing about wave engine in the wine database.

**Comment by ptupitsyn** [comment]
> I was thinking maybe we could rebuild the samples for linux with the editor.
> But the editor's installer is only available for windows and macos.

Yep, it is fine that editor is not available, but I think the resulting programs should demonstrate the cross-platform abilities of the engine, if possible.

**Comment by danielcaceresm** [comment]
Hi @ptupitsyn,

The samples can be run in Linux, but not all of them runs correctly and we decided to no publish them with Linux support until we fix the issues.
You can test to run in Linux with some changes:
- In LowLevel samples, you can select the graphics backend in the Program.cs file. Modifying the line 34, you can change the GraphicsBackend enum value to Vulkan.
- To run High level samples (like NET5Demo, AreaLightsDemo,...) it's not that easy, but basically the steps are:
  - Change WaveEngine.Forms and WaveEngine.DirectX11 nugets to WaveEngine.SDL and WaveEngine.Vulkan.
  - Replace FormsWindowsSystem to SDLWindowsSystem in Program.cs
  - Replace DX11GraphicsContext to VKGraphicsContext in Program.cs
  - In weproj file change the property GraphicsBackend of the profile, to Vulkan.

**Comment by ptupitsyn** [comment]
@danielcaceresm thank you! It works :+1:
