### ISSUE TITLE
Errors concerning the .NETFramework prevent any projects from running

### ISSUE THREAD

**Issue by sarah-graf** [WaveEngine/Feedback#42]
Hello! When runnig any of the demo-projects or creating my own project I get this pile of errors and cant build them. Could anyone tell me what I need to do to get them running?

`error NU1202: Das Paket WaveEngine.DirectX11 3.1.0.6468-preview ist nicht mit net50-windows (.NETFramework,Version=v5.0,Profile=windows) kompatibel. Paket WaveEngine.DirectX11 3.1.0.6468-preview untersttzt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)

error NU1202: Das Paket WaveEngine.HLSLEverywhere 3.1.0.6468-preview ist nicht mit net50-windows (.NETFramework,Version=v5.0,Profile=windows) kompatibel. Paket WaveEngine.HLSLEverywhere 3.1.0.6468-preview untersttzt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)

error NU1202: Das Paket WaveEngine.XAudio2 3.1.0.6468-preview ist nicht mit net50-windows (.NETFramework,Version=v5.0,Profile=windows) kompatibel. Paket WaveEngine.XAudio2 3.1.0.6468-preview untersttzt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)

error NU1202: Das Paket WaveEngine.Forms 3.1.0.6468-preview ist nicht mit net50-windows (.NETFramework,Version=v5.0,Profile=windows) kompatibel. Paket WaveEngine.Forms 3.1.0.6468-preview untersttzt Folgendes: net50-windows7.0 (.NETFramework,Version=v5.0,Profile=windows7.0)

error NU1201: Das Projekt AreaLightsDemo ist nicht mit net50-windows (.NETFramework,Version=v5.0,Profile=windows) kompatibel. Das Projekt AreaLightsDemo untersttzt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)

error NU1201: Das Projekt AreaLightsDemo.Editor ist nicht mit net50-windows (.NETFramework,Version=v5.0,Profile=windows) kompatibel. Das Projekt AreaLightsDemo.Editor untersttzt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)`

**Comment by danielcaceresm** [comment]
Hi @sarah-graf

Try to build the Windows solution directly from Visual Studio and ensure all needed tools are installed on the system.

Check that Visual Studio versions and workloads required are installed:
"Version 16.8 or greater with '.NET desktop development' and 'Universal Windows Platform development' workloads are required."

**Comment by danielcaceresm** [comment]
I will close the issue due to inactivity.
