### ISSUE TITLE
Cannot get "My first application" recipe to run with "CreateScene" code

### ISSUE THREAD

**Issue by moses70** [WaveEngine/Feedback#45]
Hi,

I am interested in using the wave engine for a factory simulation project. For that, I intend to create most of the scene programmatically.
In order to learn, I tested the "My first application" recipe (http://doc.waveengine.net/recipes/GettingStarted/My-First-Application.html) in the new 3.1 preview.

There were a few differences in the API but it seemed straight forward. But in the end, the cube is never showing up in the Viewer.

All enties from the editor are working fine.

It would be great to have a pointer here. I would offer to write a new tutorial afterwards.

**Comment by moses70** [comment]
Update:
I got the rotating cube working. The missing part was: 
 
```
 // load some material
 var material = this.Managers.AssetSceneManager.Load<Material>(WaveContent.Materials.DefaultMaterial);
 // assign to MaterialComponent:
 .AddComponent(new MaterialComponent() { Material = material })
```

Now I am searching for the right place the update the scene. May I keep the issue open for a few days?
It seems that there is some need for examples.

**Comment by vicfergar** [comment]
Hi @moses70,

The right place to include logic that has to be executed every update is creating a behavior. For this just create a class that extends from WaveEngine.Framework.Behavior as follows:

```
public class MyBehavior : Behavior
{
    protected override void Update(TimeSpan gameTime)
    {
        // My update logic goes here
    }
}
```

If you need it, you can declare dependencies with other components inside the class body as follows:
```
public class MyBehavior : Behavior
{
    [BindComponent]
    protected Transform3D transform;

    [...]
}
```

You are right, we have to improve in the documentation side and update existing recipies to the latests version.
Hope it was useful for you!

**Comment by moses70** [comment]
Hi Victor,
thank you very much for this tips! There is some progress!

Currently, I am struggling a bit with materials:
How can I create a simple colored material? 
Currently, I can only load it from assets. Can I modify it programmatically afterwards? Or better from scratch?

Another question would be about the camera movement. The default camera seems to be suitable for a game, but not so much for a simulation system. I would prefer a control scheme like in an CAD software.
Could you give me a hint how to find a suitable component?

I would love to contribute somehow, especially for industry use cases of wave engine. Maybe I am able to, after a while.

**Comment by vicfergar** [comment]
Hi again @moses70,

**Materials**
According to your materials question: Yes you can, first you have lo load the effect asset. That is:
`var standardEffect = this.Managers.AssetSceneManager.Load<Effect>(WaveContent.Effects.StandardEffect);`

Then create a material using this effect, and use a Decorator for easy property setup:
```
var standardMaterial = new Material(standardEffect); // Material instance
var standardDecorator = new StandardMaterial(standardMaterial); // Material decorator
```
If you load a material asset, use a material decorator to modidy its properties the same way as before.

**Meshes**
As I can understand, you have meshes data (Index and Verttext buffers) that you whant to represent using _MeshComponent_ and _MeshRenderer_.
For this you have to create a Model and asign it to the MeshRenderer component. Let me share with you a Helper class that can be useful for you this task:
[ModelExtensions.zip](https://github.com/WaveEngine/Feedback/files/5720840/ModelExtensions.zip)

**Camera**
As you probably notice the camera movement is fully personalizable. Maybe you want something more similar to the camera used in the [Wave GLTF Viewer](http://gltf.waveengine.net/). Let me share with you the camera components that can be useful as reference:
[Camera.zip](https://github.com/WaveEngine/Feedback/files/5720841/Camera.zip)

**Comment by moses70** [comment]
Hi Victor,

thank you so much for all the help! I got most of it working.

Only the camera behavior seems to be not working out of the box.
This code here is not able to find the relevant transforms:
```
      protected override bool OnAttached()
      {
         if (!base.OnAttached())
         {
            return false;
         }

         var child = this.Owner.ChildEntities.FirstOrDefault();
         this.targetTransform = child?.FindComponent<Transform3D>();
         var grandChild = child?.ChildEntities.FirstOrDefault();
         this.cameraTransform = grandChild?.FindComponent<Transform3D>();

```
In my scene, the camera does not have any children. I suppose the code has to be adapted to the new camera setup. I was able to find one of the transform but I have no idea about the other one.
What can we do here?

The mesh and material is working, I only wonder how I can deal with meshes with more than 65K vertices.

**Comment by vicfergar** [comment]
Hi @moses70,

Looks like I missed that part. The entity hierarchy that should be used with these behaviors is as the following:

- **Entity: cameraRig**
  - Transform3D
  - MouseCameraBehavior
  - TouchCameraBehavior
  - **Entity: anchor**
    - Transform3D
    - **Entity: camera**
      - Transform3D
      - Camera3D

As you will notice the **camera** entity will rotate and zoom around the **anchor** entity

I will share with you also the current code from the FreeCamera3D behavior. This one is much simpler and probably a good starting point for reference.
[FreeCamera3D.zip](https://github.com/WaveEngine/Feedback/files/5735233/FreeCamera3D.zip)

**Comment by moses70** [comment]
Now it works, thank you!
This is exactly what I was looking for. I only adjusted the deltas a bit.

**Comment by vicfergar** [comment]
I'm glad to have been of help.

By the way: Merry Christmas!
