### ISSUE TITLE
Wave engine is stuck at splash screen

### ISSUE THREAD

**Issue by TheKing009** [WaveEngine/Feedback#46]
Hello.
I downloaded Wave Engine v3.1 today and after installing it and .NET Runtime, the engine is still stuck at the starting splash screen.
Are there any more 3rd party software that need to be installed in order to run Wave Engine or am I missing something else?

**Comment by danielcaceresm** [comment]
Thanks you for reporting the issue.

Can you provide more information about your environment (OS and Visual Studio versions, CPU, GPU, ...)?

Also, check that Visual Studio versions and workloads required are installed:
"Version 16.8 or greater with '.NET desktop development' and 'Universal Windows Platform development' workloads are required."

**Comment by danielcaceresm** [comment]
I will close the issue due to inactivity.
