### ISSUE TITLE
hello,

### ISSUE THREAD

**Issue by Frostie-was-taken** [WaveEngine/Feedback#47]
i am frostie, my discord is "Frostie#8802" i would like to limit the resolution to 84x48 for the nokia 3310 game jam
and if it already is there, someone tell me

**Comment by Jorgemagic** [comment]
Hi Frostie,

WaveEngine uses a WindowsSystem implementation in each platform. For example in the Windows project template, you can find it in the **Program.cs** file _(1280x720 by default)_.

```
 static void Main(string[] args)
        {
            // Create app
            MyApplication application = new MyApplication();

            // Create Services
            uint width = 1280;
            uint height = 720;
            WindowsSystem windowsSystem = CreateWindowSystem();
            application.Container.RegisterInstance(windowsSystem);
            var window = windowsSystem.CreateWindow("$safeprojectname$", width, height);
```

However, the Android Windows System creates an Android view with the native device resolution. Anyway if you want to change the Swapchain/Main framebuffer resolution. You can do it in the **MainActivity.cs** file in Android project template _(Device resolution by default).

```
private void ConfigureGraphicsContext(MyApplication application, Surface surface)
{
            GraphicsContext graphicsContext = new VKGraphicsContext();
            graphicsContext.CreateDevice();
            SwapChainDescription swapChainDescription = new SwapChainDescription()
            {
                SurfaceInfo = surface.SurfaceInfo,
                Width = surface.Width,
                Height = surface.Height
```

**Comment by Frostie-was-taken** [comment]
thank you for telling me how to use iT

>
