### ISSUE TITLE
[GLTFViewer] Si haces zoom hasta el interior del modelo 3D, luego ya no puedes salir

### ISSUE THREAD

**Issue by gabrielgt** [WaveEngine/Feedback#5]
Probando la demo de http://gltf.waveengine.net/ he visto que si haces zoom hasta el interior del modelo 3D, luego ya no puedes salir.

**Comment by MarcosCobena** [comment]
Hola Gabriel:

Gracias por reportarlo :-)

Creí haberlo corregido pero acabo de probar en escritorio (con el ratón) y sigue ocurriendo.

Creo el bug a nivel interno y dejo este abierto hasta que lo pueda corregir (espero esta semana o la próxima).

—Marcos

**Comment by MarcosCobena** [comment]
Corregido @gabrielgt, ¿podrías por favor probar de nuevo y confirmárnoslo? :-)

**Comment by gabrielgt** [comment]
Comprobado. Ya funciona perfectamente.
¡Gracias!
