### ISSUE TITLE
Where is the 2D support?

### ISSUE THREAD

**Issue by frankhaugen** [WaveEngine/Feedback#55]
On the website there are references to 2D support and digging into the docs indicate that there are.

However in the UI there are only references to 3D objects.

What am I doing wrong?

**Comment by Hromon** [comment]
Yes, it support. Just install nuget pakage NoesisGUI.

![image](https://user-images.githubusercontent.com/29508584/106404234-4188c180-6443-11eb-9d61-ebaefbfaad07.png)

And do not forget press checkbox in top)

**Comment by minolo** [comment]
Hello there!

The existing documentation refers to the old WaveEngine version 2.5. We are now in the process of rewriting the entire engine, and some parts like the support for sprite sheets is still not ported to the new version 3.1, hence why it's still in preview phase.

However, if you want to draw 2D interfaces, you can use Noesis, which is pretty much integrated into WaveEngine. You can check #22 for more info on this.

**Comment by petrov-ab** [comment]
I have similar question. We need 2D project, not GUI only. Can we create it with current version WaveEditor?

**Comment by frankhaugen** [comment]
@minolo so what you are saying is that I cannot use WaveEngine 3.1 for something like a 2D platformer. At least not in a non- hacky way?

**Comment by petrov-ab** [comment]
I am still studying WaveEngine, it is easier for me to understand when there are examples

**Comment by minolo** [comment]
@frankhaugen that's correct

@petrov-ab I'm afraid not, as 2D features are still not ported to 3.1
