### ISSUE TITLE
New Project Does Not Load

### ISSUE THREAD

**Issue by eth5881** [WaveEngine/Feedback#6]
Hello! Upon creating a new project and attempting to open it, the project fails to build. The output window contains these messages:

Current project path: "C:\projects\Paratrooper\Paratrooper.weproj"
Starting build script '"Content\waveeditor.build.ps1"' with '"C:\projects\Paratrooper\Paratrooper.Windows.sln"' for the project '"Paratrooper.Windows"'
The project build has failed.

I am using Wave Engine 3.0. Not sure if it's something with my installation, but Wave Engine 2.5.0 also does not load. When attempting to open it, I receive a "Render Exception" error:

HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

I really like what I'm seeing from your engine and would love to use it on my project, but I can't seem to get it up and running. I'm hoping you can help. Thanks!

**Comment by danielcaceresm** [comment]
Hi @eth5881,

Thanks you for reporting the issue.
About the Wave Engine 3.0 issue, appears that the script that builds the project can not be executed.
A weird issue that we have identified is that some machine can not locate poweshell. Can you test to open a cmd an execute "powershell.exe"? If the cmd returns an error indicating that the command is not recognized, this is causing the issue and you can test the following link: https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

Sorry for the inconveniences.

**Comment by danielcaceresm** [comment]
I’m closing this issue now. Please reopen if you still encounter this issue :)

Thank you!
