### ISSUE TITLE
Can't log in Editor v 2.5

### ISSUE THREAD

**Issue by petrov-ab** [WaveEngine/Feedback#60]
Hi guys,
after installation of the editor WaveEngine v.2.5, I created an account on waveengine.net.
But when I run the editor and try to sign in with this account, I get a "Deserializer message error" error message.
The editor's log says the following:

12 Feb 2021 08:50:49,546 ERROR - AuthenticationService |    в System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   в System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   в System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   в WaveEngine.Common.Serialization.SerializerJson.Deserialize(Stream stream)
   в WaveEditor.Core.Services.SerializationService.Deserialize[T](Stream stream, SerializationType serializationType)
   в WaveEditor.Core.Services.AuthenticationService.<LoginRequest>d__19.MoveNext()

What's the matter here?

**Comment by q0099** [comment]
Hello. It seems I figured out what was an issue.
While logging in, the editor is trying to make an authorisation post request to the host "www.waveengine.net", which redirects it to the "waveengine.net" and, it seems, the redirection is handled kinda wrong, so the editor takes the error page for a response (thus the "deserializer message error" message).
If you intercept the authorisation request (with Fiddler, for example), you can modify it's host to "waveengine.net" and authorisation would be done just fine.

**Comment by petrov-ab** [comment]
Thanks, it works.
After installing Fiddler I made a rule in OnBeforeRequest
if (oSession.HostnameIs("www.waveengine.net")) {
			oSession.hostname="waveengine.net";
		}
Then I turned on the option "decrypt https traffic" and received a certificate from Fiddler.
This is a prerequisite.  After that, WaveEditor v.2.5 started normally
