### ISSUE TITLE
Editor does not show my behavior class from referenced project

### ISSUE THREAD

**Issue by JohnMasen** [WaveEngine/Feedback#62]
repro steps:
1. create a new DX11 project in WaveEditor [Name=MyTest]
2. open the new project with VisualStudio 2019
3. add a new netcore 2.0 project [Name=MyLib]
4. add nuget reference to WaveEngine.Components and create a class inherits Component [Classname=MyBehavior]
5. add project reference [MyTest -> MyLib]
6. Reload WaveEditor, found the output windows shows MyLib was successfully compiled
7. Create a new entity in MyScene
8. Click "Add Component"

Expected result:
MyBehavior is in the Component List

Actual result:
MyBehavior is not in the Component List

PS: I tried to create a new class[ ClassName=MyNewBehavior] inherits MyBehavior in project MyTest, the inherited class will be in the add components list and works just fine. this means the base class has already been loaded by the Editor, but seems there's some bug prevents class loaded from referenced project.
PS2: the MRTK project seems does not have this issue, components from the referenced project WaveEngine.MRTK are in the add component list, I tried to find out why, but still no clue.

**Comment by danielcaceresm** [comment]
Hi @JohnMasen,

Apologies for the delayed response.

The editor shows the components from all referenced assemblies that has the following assembly attribute:
[assembly: WaveEngineAssembly(WaveAssemblyUsage.UserProject)] 

You can copy the file Properties/AssemblyInfo.cs from MyTest project to your MyLib project.

**Comment by danielcaceresm** [comment]
I will close the issue due to inactivity.

**Comment by JohnMasen** [comment]
sorry for the late response. you suggestion solved my issue. 
Thanks denielcaceresm.
