### ISSUE TITLE
WaveEngine 3.1 - Efficiently Create 3D Lines? (in large quantities)

### ISSUE THREAD

**Issue by Perimint** [WaveEngine/Feedback#63]
Hello,

I'm using the 3.1 preview and I'm really enjoying it so far.

In my project I need to draw many lines, often hundreds of thousands of them.  I'm doing this currently by creating 12 triangles to form a rectangular prism for each line I want to display and using the code previously shared by @vicfergar (https://github.com/WaveEngine/Feedback/issues/45#issuecomment-748594970) to turn those triangles into a mesh.  This works, but can have performance issues depending on how many lines I need.

Is there a different method I can use to more efficiently create these lines?  I know in some 3D engines you can draw a line using two vertexes (for example: https://stackoverflow.com/questions/38067867/how-do-i-draw-a-simple-line-in-qt3d).  Is a similar method possible in WaveEngine 3.1?

Ideally I would like the line to appear to the user as an elliptical prism:

![image](https://user-images.githubusercontent.com/69114389/108598434-82496b80-735b-11eb-8c48-4b9c35a46cdf.png)

where I can adjust the A and B values possibly by using different shaders (or whatever makes the most sense).  This would be way too intensive (on memory and processing) with my current method, which is why I am currently using a rectangular prism.

Thank You!

**Comment by vicfergar** [comment]
Hi @Perimint, 

We are glad you are enjoying using the engine. As you said there is a more efficient way of drawing 3D lines. To do so, you need to use the `LineBatch3D` within a `Component` as follows:

```
public override void Draw(DrawContext drawContext)
{
    this.RenderManager.LineBatch3D.DrawLine(Vector3.Zero, Vector3.One, Color.Tomato);
}
```

**Comment by adamthole** [comment]
Hi @vicfergar,

Thank you for the quick reply!  I created a class where I inherit from Drawable3D and override the Draw method as you showed and it works great.

Is it possible to change the look of how the line is rendered?  I see that I can change the color easily, but is it possible to change the diameter / thickness of the line?

Thanks!

**Comment by vicfergar** [comment]
Hi @adamthole,

LineBatch3D is usually used for debug purposes so no style can be given to the lines. If you need something more stylish try using the `LineMesh` and `LineMeshRenderer3D` components as follows:

 ```
var lineMesh = new LineMesh();
lineMesh.LineType = LineType.LineList;
lineMesh.LinePoints = new List<LinePointInfo>()
{
    new LinePointInfo()
    {
        Position = Vector3.Zero,
        Color = Color.Tomato,
        Thickness = 0.1f,
    },
    new LinePointInfo()
    {
        Position = Vector3.One,
        Color = Color.Green,
        Thickness = 0.1f,
    },
};

var lineContainer = new Entity()
                .AddComponent(new Transform3D())
                .AddComponent(lineMesh)
                .AddComponent(new LineMeshRenderer3D());
```

**Comment by adamthole** [comment]
Hi @vicfergar,

Thanks again for the response!

Is there a way to get the lines created by LineMeshRenderer3D to have a height?  My issue with them is that they are 2D lines in 3D space, so when viewed from the side they disappear.  What I'm looking for is a 3D line, essentially a cylinder but without all the triangles.

Thank you!

**Comment by vicfergar** [comment]
Hi again @adamthole,

Try with `LineMesh.IsCameraAligned = true;`

**Comment by adamthole** [comment]
Hey @vicfergar,

Thanks, that helps significantly!  This will work great for displaying lines that have the same height and thickness.

For a line that has (for example) a thickness of 1 and a height of 0.25 do you have any suggestions on a method to display that correctly?

Thanks!

**Comment by vicfergar** [comment]
Hi @adamthole,

I think that I dont understand your question. Using `LinePointInfo` you define the properties of the line each point. When working with `LineType.LineList` each two points define a segement, the length of that segment is determined by the start and end points.

**Comment by adamthole** [comment]
Hi @vicfergar,

Thanks again for the replies.

In the end I want to modify three parameters for the line: length, width, height.

Length: As you mentioned, this is set by the start and end points.
Width & Height: Using the LinePointInfo Thickness I can set one of these.  It is truly a line in that it is 2D in a 3D space, so when viewed from the side it disappears.  Using the IsCameraAligned option I can make it look like it has a width and height, but they are both the same (the Thickness value). Width = Height = Thickness

Is there a way I can make it look like I have a different Width and Height for the defined line?

**Comment by vicfergar** [comment]
Hi @adamthole, 

Again I don't understand your point. There are only two variables for a 3D line `Thickness` and `Length`. I cannot see how `Width` and `Height` apply in this case.

**Comment by vicfergar** [comment]
I saw the first post and I think that your are using two different accounts @Perimint and @adamthole.

I the case you want the line to looks like a rectangular prism, it could be better to change the line thickness retalive to camera position within the shader. You can do so modifiying the `LineEffect` in your project assets.

**Comment by Perimint** [comment]
@vicfergar You are correct about the two different accounts.  This one is for my company and the other one is my personal account.  Sorry for the confusion!

That makes perfect sense on the `LineEffect` shader, thank you for pointing me in the right direction.  

You've answered my question so I will close this issue.  Thanks again!
