### ISSUE TITLE
"MSBuild not found" error whenever I open Wave

### ISSUE THREAD

**Issue by ghost** [WaveEngine/Feedback#66]
![Untitled (23)](https://user-images.githubusercontent.com/68661495/110374823-27806700-801f-11eb-86fc-c407316c6eab.png)

I'm brand new to Wave, (I've used other engines, mainly js-based engines and made 5 games) this is the first ever time I'm using it, and when I open a wave project it says that "MSBuild not found", I tried making a new project, same thing, anyone know how to fix it?

**Comment by mobilex1122** [comment]
Yes, I have same problem.

**Comment by danielcaceresm** [comment]
Hi @SaberTooth-Studios @mobilex1122,

Check that Visual Studio versions and workloads required are installed:
"Version 16.8 or greater with '.NET desktop development' and 'Universal Windows Platform development' workloads are required."

**Comment by danielcaceresm** [comment]
I will close the issue due to inactivity.
