### ISSUE TITLE
[GLTFViewer] Error loading file: System.ArgumentException: Path is empty

### ISSUE THREAD

**Issue by Nikola43** [WaveEngine/Feedback#7]
**TODO** please attach the file used so we can debug it —we will keep it private if you send such by [e-mail](mailto:mcobena@plainconcepts.com).

# Error
```
System.ArgumentException: Path is empty
Parameter name: absoluteDirectoryPath
  at GLTFViewer.GLTF.LoadAsync (System.String absoluteDirectoryPath) [0x00020] in C:\Users\Marcos\Repositorios\Wave.GLTFViewer.Web\src\GLTFViewer\GLTF.cs:27 
  at GLTFViewer.MyScene.AddGLTFAsync (System.String absoluteDirectoryPath) [0x00053] in C:\Users\Marcos\Repositorios\Wave.GLTFViewer.Web\src\GLTFViewer\MyScene.cs:35 
  at GLTFViewer.Web.Program+<>c__DisplayClass5_0.<LoadGLTF>b__0 () [0x0006e] in C:\Users\Marcos\Repositorios\Wave.GLTFViewer.Web\src\GLTFViewer.Web\Program.cs:92 
```

**Comment by MarcosCobena** [comment]
Hola @Nikola43:

Gracias por reportar el fallo.

Por el call stack, tiene pinta que se ha invocado la carga del modelo antes de que se copiara en el VFS que crea Emscripten (básicamente, se copia en memoria).

Me ha comentado @migueBarrera que volviste a recargar la página y te funcionó, y que usaste este enlace: http://gltf.waveengine.net/?model=https://wave.blob.core.windows.net/models/PiggyBot.glb

¿Te volvió a ocurrir, podrías por favor probar de nuevo limpiando la caché (F12, Red, deshabilitar caché)?

Solo se me ocurre que no haya dado tiempo a la copia en el VFS, y por eso el directorio esté aún vacío, pero no debería ocurrir...

Gracias de nuevo,

—Marcos

**Comment by Nikola43** [comment]
Hola Marcos, voy a intentarte detallartelo lo mejor posible

Al abrir el enlace parecía estar tardando mucho en cargar,
pero teniendo en cuenta lo que me contó Miguel sobre Waves
carga un modelo en 3d en un navegador, pensé que era normal que tarde un
poco.
Pasado aproximadamente unos 30-45 segundos la animación de carga parecía
estar en bucle
hasta que mostró un alert diciendo que había un error y que por favor se
reportará.
Una vez reportado lo abrí de nuevo y funcionó perfectamente.
El error fue usando Chrome

He estado haciendo unas pruebas y no he conseguido reproducirlo de nuevo
así que te felicito por ello.

Pruebas realizadas:
Borrar todos los datos de navegación (Historial, cache, cookies)
Entrar en modo incógnito
Deshabilitar cache

Equipo:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2,3 GHz Intel Core i5 de doble núcleo
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 640 1536 MB

OS:
MacOS Catalina 10.15.2 (19C57)

Navegadores usados para las pruebas:
Firefox 73.0.1 (64-bit)
Chrome 79.0.3945.130 (64 bits)
Safari 13.0.4 (15608.4.9.1.3) (64 bits) (Me sale error no compatible)
Opera 66.0.3515.103  (64 bits)

**Comment by MarcosCobena** [comment]
Muchas gracias por todos los detalles, ¡ojalá siempre fuesen así los reportes de bugs! :-)

Es normal que no te funcionase en Safari, por ahora no soportan de forma estándar WebGL en su versión 2.0, que es el backend que usamos hoy día.

De nuevo, gracias por tu tiempo :-)

PD: acabamos de lanzar nueva versión, si vuelves a probar verás que la espera se hace un poco más llevadera al menos :-)

**Comment by MarcosCobena** [comment]
Déjame cerrar la issue si en principio no se ha vuelto a reproducir el problema; siéntete libre de reabrirla por favor si ves que vuelve a ocurrir 🤞😊
