### ISSUE TITLE
FBX Support in WaveEngine

### ISSUE THREAD

**Issue by sarath-vanga** [WaveEngine/Feedback#72]
Does WaveEngine uses Autodesk FBX SDK to read the .fbx files ?

**Comment by minolo** [comment]
Hi there.

WaveEngine uses [FBX2glTF](https://github.com/facebookincubator/FBX2glTF) to convert FBX to GLTF and then imports that converted file. The FBX2glTF project uses Autodesk's FBX SDK.

I hope I've been helpful!

**Comment by sarath-vanga** [comment]
Yes Thanks.
