### ISSUE TITLE
WaveEngine 3 preview: WPF multiple integration

### ISSUE THREAD

**Issue by BChapoulie** [WaveEngine/Feedback#76]
Hi, 

I am trying to integrate WaveEngine inside a WPF application. To do so I've followed the example given there and it works: 
https://github.com/WaveEngine/UIWindowSystemsDemo/tree/main/UIWindowSystemsDemo.WPF

However, I am now trying to have multiple views integrated in one single WPF application. So I have two WaveContainer WPF Content which contains a respective Display created like in the example. But I manage to only have one or the other content, never both of them in the same time. The SurfaceUpdated method also takes a display to tell to which Display it should be drawn.

For now I have just one scene as it is some testing.
Here are a code sample I modified from the example to try and achieve my goal:

```csharp
        private void LoadWaveEngineControl()
        {
            _graphicsContext = _waveApplication.Container.Resolve<DX11GraphicsContext>();

            var display2D = new Display(Surface2D, (FrameBuffer)null);
            Surface2D.SurfaceUpdatedAction = surfaceHandle => SurfaceUpdated(surfaceHandle, display2D);

            var display3D = new Display(Surface3D, (FrameBuffer)null);
            Surface3D.SurfaceUpdatedAction = surfaceHandle => SurfaceUpdated(surfaceHandle, display3D);

            WaveContainer2D.Content = Surface2D.NativeControl;
            Surface2D.NativeControl.MouseDown += NativeControlMouseDown;
            WaveContainer3D.Content = Surface3D.NativeControl;
            Surface3D.NativeControl.MouseDown += NativeControlMouseDown;

            var graphicsPresenter = _waveApplication.Container.Resolve<GraphicsPresenter>();
            graphicsPresenter.AddDisplay("Display2D", display2D);
            graphicsPresenter.AddDisplay("Display3D", display3D);
        }
```
Surface2D and Surface3D are WPFSurface objects.

I have tried creating two distinct WaveApplication (with distinct services) but it didn't work either. I saw on Twitter that someone managed to do it but didn't find further documentation nor examples I didn't manage to reproduce it (https://twitter.com/jorge_magic/status/1090261897100681217).
I don't manage to get the grasp on what I am missing there so if I could have a few guidelines on how to achieve my goal, it'd be much appreciated.

**Comment by danielcaceresm** [comment]
Hi @BChapoulie,

I think you are only missing to add a new camera to the scene that uses the new display.
In the following [branch ](https://github.com/WaveEngine/UIWindowSystemsDemo/tree/feature/multipleDisplay) I have upload a sample, where I have added a second camera to the Scene, and it is using the display with the tag 'Display2'. 

In the twitter link my teammate are running two different scenes in each display. For that, you must specify the tag of the second display in the camera of the second scene and run both scenes in the same ScreenContext in the file MyApplication.cs:
`
            base.Initialize();

            // Get ScreenContextManager
            var screenContextManager = this.Container.Resolve<ScreenContextManager>();
            var assetsService = this.Container.Resolve<AssetsService>();

            // Navigate to scene
            var scene = assetsService.Load<MyScene>(WaveContent.Scenes.MyScene_wescene);
            var scene2 = assetsService.Load<MyScene>(WaveContent.Scenes.MyScene_1_wescene);
            ScreenContext screenContext = new ScreenContext(scene, scene2);
            screenContextManager.To(screenContext);`

Hope this helps!

**Comment by BChapoulie** [comment]
Hi @danielcaceresm,

Thank you very much for your reply, I was indeed missing the DisplayTag on the camera component. I have tried with the same scene and with two different scenes and it works fine!
I am looking forward to explore even more WaveEngine.

**Comment by danielcaceresm** [comment]
Hi @BChapoulie,

I am glad that it has helped you.

I will close the issue.
Thanks you.
