### ISSUE TITLE
Error when trying to start wave engine 3.2 preview. 

### ISSUE THREAD

**Issue by HeadClot** [WaveEngine/Feedback#78]
Hey - I have recently installed wave engine and I am getting the following error when I try to start wave engine.

![Capture_WaveEngine](https://user-images.githubusercontent.com/1534098/117247458-7d914100-adfb-11eb-8c78-6d615cd38da9.PNG)

"There was an error preparing WaveEngine Editor to Run.
Please check your internet connection and try again"

**Comment by danielcaceresm** [comment]
Hi @HeadClot,

Could you check if a log file is created in "%LOCALAPPDATA%\WaveEngine\Launcher\3.2.0.7766\logs"?
Also, can you check if the folder "%USERPROFILE%\\.waveengine" has been created? If it is there, you can try to remove it and open Wave Engine again.

**Comment by HeadClot** [comment]
Hey @danielcaceresm I am not seeing any logs folder or log files in the folder specified. As for the .waveengine folder I just deleted it and the engine now works :)

**Comment by danielcaceresm** [comment]
Hi @HeadClot,
 
I am glad that it has helped you.
Appears that there was some issue downloading the Wave Engine editor, and the launcher could not be able to recover from this state. We must work harder to make this process more reliable :muscle:.

I will close the issue.
Thanks you.
