### ISSUE TITLE
Using System Fonts

### ISSUE THREAD

**Issue by aspernol** [WaveEngine/Feedback#8]
Hi,
I'm not sure if this is the correct platform but I couldn't find a forum or so.
I have to maintain some C# code using WaveEngine 2.4.1 and I want to use TextComponent objects and TextRenderer3D to display some text. The user should be able to select the font from a list of fonts (ideally the system fonts). I tried out a lot of different things but couldn't find a solution.

**Comment by minolo** [comment]
Hi there. Thanks for the feedback!

Unfortunately we have stopped supporting WaveEngine 2 and have focused on WaveEngine 3 development, so it is not very likely that this will be implemented in the future.

However, you should be able to import fonts using the editor and they will be available for use in your TextComponents. Just drag your font file into the assets folder in the editor and they will be imported.

I hope this helped. Regards.

**Comment by MarcosCobena** [comment]
Hi @aspernol,

Just 2 cents more: we still have available those recipes applying to prior versions, like this one where you can learn how to add custom fonts:

https://github.com/WaveEngine/Documentation/blob/master/recipes/UI/Add-Custom-Fonts.md

You could add every font needed through above recipe and, during execution, let the user choose between them.

—Marcos

**Comment by aspernol** [comment]
Hi,
thanks everybody for your replies. I will try to implement it that way. Hopefully in the future we will be able to upgrade WaveEngine in our software.
Just out of curiosity: Will this be available in a future version?
Best regards,
Andreas.
