### ISSUE TITLE
Error al guardar un archivo después de renombrarlo

### ISSUE THREAD

**Issue by gabrielgt** [WaveEngine/Feedback#9]
Hola,

En la versión 3.0.0.4567-preview3 se produce el siguiente error:

![image](https://user-images.githubusercontent.com/3408827/76644636-aef3e100-6557-11ea-9b11-0873bb910ed0.png)

Se reproduce fácilmente de la siguiente manera:
- Hacer doble click en un asset para abrir sus propiedades. Por ejemplo, un material.
- Renombrar el fichero del asset.
- Modificar alguna propiedad, por ejemplo, el color.
- Intentar guardar los cambios.

![image](https://user-images.githubusercontent.com/3408827/76644687-cc28af80-6557-11ea-8bd4-26370f82240b.png)

Hasta que no se cierra el editor no se soluciona el problema y se pierden los cambios realizados después del renombrado. 

¡Saludos!

**Comment by danielcaceresm** [comment]
Hola @gabrielgt,

Muchas gracias por informar del problema. He podido reproducirlo y lo intentaremos corregir para la siguiente actualización.
Te informo por aquí cuando publiquemos la versión que lo soluciona.

Un saludo.

**Comment by danielcaceresm** [comment]
Hola @gabrielgt,

Acabamos de publicar una actualización de la preview 3, la versión 3.0.0.4636-preview3, que soluciona este bug.
Cierro la issue, no dudes en volver a abrirla si el bug sigue.

Muchas gracias.

**Comment by gabrielgt** [comment]
Comprobado. Ya funciona perfectamente.

¡Gracias!
