### ISSUE TITLE
Showing Wave Engine Error

### ISSUE THREAD

**Issue by algoscienceacademy** [WaveEngine/Feedback#91]
![20210823_140815](https://user-images.githubusercontent.com/76747815/130434548-21aa9f4a-8151-481f-9c25-3e20161003cd.jpg)
![20210823_140802](https://user-images.githubusercontent.com/76747815/130434586-f4b00822-7954-4805-936a-f54f96e2c2d6.jpg)
I saw such an error after downloading the wave engine. Now I do not understand what to do?
Please help!! Is there any  software / tools Required I need to install before downloading wave engine!

**Comment by algoscienceacademy** [comment]
![20210828_130718](https://user-images.githubusercontent.com/76747815/131209886-8bcde90d-8a55-4a12-89b2-49378c195d9a.jpg)
![20210828_130855](https://user-images.githubusercontent.com/76747815/131209887-b375644d-37f9-4bdb-860e-63021f77c86c.jpg)
After giving the results came. I have VS 16.11.2. Did I skip downloading any important VS tools? And what do I do now?

**Comment by minolo** [comment]
Hi!

I would guess you are missing MSBuild. Please check that you have the correct workloads installed. For this:
- Open the Visual Studio Installer and click the "Modify" button on your Visual Studio installation.
- Select the '.NET desktop development' and 'Universal Windows Platform development' workloads.
- Click the "Modify" button to install the components.

![image](https://user-images.githubusercontent.com/6577955/131223767-810a3889-6728-4c09-8272-3f3bfbcec332.png)

I think that will fix your issue, but please do tell us about your results.

Have a nice one!

**Comment by algoscienceacademy** [comment]
![20210830_151254](https://user-images.githubusercontent.com/76747815/131317442-11688fca-73ec-411c-9a67-8169d1540b89.jpg)
Thank you. Thank you so much Much. My problem has been solved. Sorry for the inconvenience. But Thanks Many Many 😊😊
